version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: appimage
    container_name: App
    restart: unless-stopped
    volumes:
      - ./app:/var/www

  webserver:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: webserverwmage
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
    - ./app:/var/www
    - ./config/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
