FROM node:16-alpine

WORKDIR /var/www/frontend

ENV PATH /var/www/frontend/node_modules/.bin:$PATH

COPY ./app/frontend/package.json ./
COPY ./app/frontend/package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY ./app/frontend ./

# start app
CMD ["npm", "start"]