version: "3"

services:
  # Database
  db:
    container_name: mysql-db
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  # Wordpress
  wordpress:
    container_name: wordpress-site
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes: 
      - "./CollegeQ_WordPress:/var/www/html"
      - "./TWM:/var/www/html/wp-content/plugins/TWM"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
  # React plugin
  plugin:
    container_name: tree-water-monitor-plugin
    build:
      context: "/var/www/html/wp-content/plugins/TWM"
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    volumes:
      - /var/www/html/wp-content/plugins/TWM/app/node_modules
      - ./TWM:/var/www/html/wp-content/plugins/TWM/app
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
networks:
  wpsite:
volumes:
  db_data:
