version: "3"

services:
  react:
    container_name: React
    image: reactimage
    build:
      context: .
      dockerfile: Dockerfile-react
    volumes:
      - ./app/frontend:/var/www/frontend
      - ./app/frontend/node_modules:/var/www/frontend/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: appimage
    container_name: App
    restart: unless-stopped
    volumes:
      - ./app/backend:/var/www/backend

  webserver:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: webserverwmage
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
    - ./app/backend:/var/www/backend
    - ./config/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
